### ISSUE TITLE
test example

### ISSUE THREAD

**Issue by yhgon** [MiaoLab20/gamd-openmm#18]
status mention about the `The dihedral and total boost algorithms are working and have been validated.`

could you provide any test example?

I want to duplicate the simulation in GaMD-Amber tutorial  https://miaolab.ku.edu/GaMD/tutorial.html 

thanks

**Comment by dyelar** [comment]
I'm working on that right now, along with our new front end program.  

The configuration files will be found in this additional project:

[https://github.com/MiaoLab20/gamd-openmm-tests](https://github.com/MiaoLab20/gamd-openmm-tests)
