### ISSUE TITLE
This there a bug about kdoubleprime update?

### ISSUE THREAD

**Issue by cyrushu** [MiaoLab20/gamd-openmm#19]
Dear MiaoLab scientists,

Is there a bug in the beginIfBlock since it will update all groups in calculate_common_threshold_energy_and_effective_harmonic_constant function but we only want to update the group_name k0 instead?

https://github.com/MiaoLab20/gamd-openmm/blob/main/gamd/langevin/base_integrator.py#L576
```python
            for group_id in self.get_group_dict():
                group_name = self.get_group_dict()[group_id]
                self.beginIfBlock(
                    self._append_group_name("k0doubleprime_window", group_name)
                    + " >= 0.0")
                self.calculate_common_threshold_energy_and_effective_harmonic_constant(ComputeType.GROUP)
                self.endBlock()
```

**Comment by cyrushu** [comment]
I have used the updated function with params target_group_idx/target_group_name if this would help.
```python
    def add_compute_global(self,
                           name,
                           expression,
                           format_list,
                           num_value_suffix=False,
                          target_group_idx = None,
                          target_group_name=None):
        assert self.compute_type.lower() == "group"
        for group_id,group_name in self.group_dict.items():
            if target_group_idx is not None and group_id !=  target_group_idx:
                continue
            if target_group_name is not None and group_name != target_group_name:
                continue
            var_name = "{}_{}".format(name, group_name)
            new_formats = []
            for format_str in format_list:
                if num_value_suffix:
                    new_formats.append("{}{}".format(format_str, group_id))
                else:
                    new_formats.append("{}_{}".format(format_str, group_name))
            formatted_expression = expression.format(*new_formats)
            self.addComputeGlobal(var_name, formatted_expression)
```

**Comment by cyrushu** [comment]
> I have used the updated function with params target_group_idx/target_group_name if this would help.
> 
> ```python
>     def add_compute_global(self,
>                            name,
>                            expression,
>                            format_list,
>                            num_value_suffix=False,
>                           target_group_idx = None,
>                           target_group_name=None):
>         assert self.compute_type.lower() == "group"
>         for group_id,group_name in self.group_dict.items():
>             if target_group_idx is not None and group_id !=  target_group_idx:
>                 continue
>             if target_group_name is not None and group_name != target_group_name:
>                 continue
>             var_name = "{}_{}".format(name, group_name)
>             new_formats = []
>             for format_str in format_list:
>                 if num_value_suffix:
>                     new_formats.append("{}{}".format(format_str, group_id))
>                 else:
>                     new_formats.append("{}_{}".format(format_str, group_name))
>             formatted_expression = expression.format(*new_formats)
>             self.addComputeGlobal(var_name, formatted_expression)
> ```

Since I am only working on the grouped compute_type, the compute_type is ignored

**Comment by dyelar** [comment]
We have updated the main line with several new changes, one of which should resolve this issue.  I'll close this issue, once my full test battery is complete, which generally takes about a week to run for all of the different types.  The commit tag 0.9.1 has been applied to this update.

**Comment by cyrushu** [comment]
Thanks a lot for the Update. Free to close this issue when it have been tested.
