### ISSUE TITLE
Parsing gromacs input files

### ISSUE THREAD

**Issue by TienMPhan** [MiaoLab20/gamd-openmm#20]
Hi,

I saw in the code that GAMD-OPENMM can read gromacs input files. I tried 

```
<gromacs>
      <topology>data/input.top</topology>
      <coordinates>data/input.gro</coordinates>
      <include-dir>/usr/local/gromacs/share/gromacs/top</include-dir>
 </gromacs>
```
but it returned error:

`xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 51, column 20`

Gromacs files I took from openMM's example folder and the include-dir pointed to the folder containing the force fields. Could you please have a quick check on this?

Thanks,
Tien

**Comment by lvotapka** [comment]
Hi Tien,

Would you be able to attach your XML input file, as well as all the simulation files you are attempting to use? This would allow me to recreate the error.

**Comment by TienMPhan** [comment]
[test.zip](https://github.com/MiaoLab20/gamd-openmm/files/8584075/test.zip)

Thank you, Lane! I attached the files.

**Comment by lvotapka** [comment]
Working on this...

**Comment by lvotapka** [comment]
This was a bug that should now be fixed. Go ahead and try pulling and reinstalling before running your calculations.

**Comment by TienMPhan** [comment]
Thank you Lane! I'll give it a try.

**Comment by TienMPhan** [comment]
It works! Thanks again. I'll go ahead and close the issue.

**Comment by lvotapka** [comment]
Thanks for helping us find the bug.
