### ISSUE TITLE
Files in the output directory

### ISSUE THREAD

**Issue by TienMPhan** [MiaoLab20/gamd-openmm#21]
Hello,

I just wonder the role of `checkpoints`, `positions` and `states` in the output folder. Are they for the analysis? I plan for a long production run and these files take a lot of storage space.
I think we can use the `gamd_restart.checkpoint` to restart the simulation. I'm not sure how to use the files in those folders.

```
if (step % ntave) == 0:

    state_filename = os.path.join(output_directory, "states", str(step) + ".xml")
    step_checkpoint_filename = os.path.join(output_directory, "checkpoints",  str(step) + ".bin")
    positions_filename = os.path.join(output_directory,  "positions",  "coordinates-" + str( step) + ".csv")
    simulation.saveState(state_filename)
    simulation.saveCheckpoint(step_checkpoint_filename)
    integrator.create_positions_file(positions_filename)

```

Thanks,
Tien

**Comment by lvotapka** [comment]
Hi @TienMPhan ,

After discussing with @dyelar, we determined that these outputs weren't typically used for any analysis beyond debugging. So we've removed them from the main branch. You can also safely delete the contents of checkpoints/, positions/, and states/ to save space for yourself.

**Comment by TienMPhan** [comment]
Hi @lvotapka,

The reason I asked for this is that the performance of GaMD is much slower than the conventional simulation without potential boost (~ about 6-fold slower). At first I suspected that writing files may have slowed down the simulation. I commented out the lines and reinstalled the package but it didn't improve much.
I tested the chignolin (10 residues) system in an octahedron box length of 5nm (attached files). The system has 9318 atoms. The performance of conventional simulation on an A100 GPU ~1.1 microseconds/day while the GaMD-OpenMM is ~200 nanoseconds/day. Is this performance normal? Did you guys observe something similar when implementing the algorithm? Or something went wrong on my end?
[chignolin.zip](https://github.com/MiaoLab20/gamd-openmm/files/8628421/chignolin.zip)

**Comment by lvotapka** [comment]
Chignolin is quite a small system, so I am not tremendously surprised that you observed this slowdown. With a larger system, I suspect that you'll see less of a performance hit by using GaMD.

Nevertheless, @dyelar, we ought to do an analysis of performance comparing cMD and GaMD for different systems, and possibly on different GPU models as well (and that would be something good to add to the manuscript).

**Comment by TienMPhan** [comment]
Thanks Lane. I am looking forward to seeing the comparison in your manuscript.
